### ISSUE TITLE
Repeated expressions in the derived function result in repeated statements in the derivative.

### ISSUE THREAD

**Issue by efremale** [vgvassilev/clad#88] opened 2018-08-20 18:47 UTC
Example:
```
double f(double x, double y) {
  double t = (x - y) * (x - y);
  return t;
}
```
->
```
double f_darg0(double x, double y) {
  double _t0 = (x - y);
  double _t1 = (x - y);
  double _d_t = (1. - 0.) * _t1 + _t0 * (1. - 0.);
  double t = _t0 * _t1;
  return _d_t;
}
```
Variables `_t0` and `_t1` are redundant. Since the original function uses (x - y) on several places, we get several temporaries for it.

We do not check the original function for repeated expressions, it would add quite a huge computational overhead. Moreover, since it was acceptable for the original function to use the same expression repeatedly, it is presumably acceptable to do so in the derivative.

**Comment by grimmmyshini** [comment] 2021-06-09 08:09
In my opinion, this actually a little bit difficult to implement. Two cases arise,

1 **The same subexpression is used multiple times in the same statement (the one you mention above)**  

for statements like above, it is fairly easy to reduce redundant temporaries. However, it may be difficult to track expressions that resolve to the same value, for example, consider the following statement:

```t = (x +  z  + y) * ( y + x + z);```

while both the terms in RHS evaluate to the same value, it will be difficult for us to determine that in the clad (not to mention also extremely computationally heavy). Another case is where we modify the value of any one variable in the temporary. For example,

``` float z = (x + y) * (x++) * (x + y);```

here it is incorrect to store the value of  ```(x + y)``` in the same temporary as ```x``` is being modified mid statement. Keeping track of whether an in-statement modification was made to any of the expressions we are tracking is computationally expensive. Now, this is something we won't see very often but might be an important case to cover.

2 **Same subexpressions  across different  statements** 

This as the name suggests is even harder, we will be needing to keep track of if the variables in that specific expression have been modified or not. Let alone any other checks mentioned here, keeping track of the temporaries' information is an overhead.

It might be useful to store this information in a 'misc / developer remarks' section in the docs as opposed to in the list of issues. IMO, we should close this issue and label it appropriately so that it can be later added to the docs or a developer's manual or something of that sort. As in the issues, it gives the idea that this is something 'we should' implement/fix.

**Comment by PetroZarytskyi** [comment] 2024-05-23 19:57
I agree with the concerns of @grimmmyshini. First, we only recompute what was recomputed in the original function. Second, we would need to introduce a map from _t0's to the expression they store. Third, even that would not be enough because the same expressions might evaluate to different values in different places in the code. So we would have to perform a specific analysis to ensure the value is the same. I think it's not worth the effort.
I'm closing the issue but if somebody thinks the issue is reasonable and there are enough use cases for it, please comment and reopen.

**Closed by PetroZarytskyi** 2024-05-23 19:57 UTC
