### ISSUE TITLE
Incorrect result when calling clad::jacobian wrt given parameter

### ISSUE THREAD

**Issue by ioanaif** [vgvassilev/clad#408] opened 2022-03-23 15:23 UTC
Incorrect result when calling clad::jacobian wrt given parameter, the issue can be seen in the code below. The derivatives matrix should have contained [0, 10, 3]. 

<img width="536" alt="image" src="https://user-images.githubusercontent.com/9751871/159734256-00eb9405-a7eb-4549-9de2-f38aae7b0d57.png">

The behaviour is correct when calling clad::jacobian wrt all parameters:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/9751871/159733948-47269487-2700-444d-a43f-1b98d257e769.png">

For reference, the generated code is:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/9751871/159734397-0de31cff-606b-4f61-b2c9-a91cef89d7c5.png">

**Comment by Nirhar** [comment] 2022-03-24 17:05
I've been trying to find a solution to this issue and have narrowed the problem down to this function:
```
StmtDiff Visit(const clang::Stmt* stmt, clang::Expr* dfdS = nullptr) {
      // No need to push the same expr multiple times.
      bool push = !(!m_Stack.empty() && (dfdS == dfdx()));
      if (push)
        m_Stack.push(dfdS);
      auto result =
          clang::ConstStmtVisitor<ReverseModeVisitor, StmtDiff>::Visit(stmt);
      if (push)
        m_Stack.pop();
     return result;
   }
```
The above function is a part of ReverseModeVisitor Class and is called by the derive function of ReverseModeVisitor, with the body of the function to be differentiated. I dumped the result given by the function Visit for the case described by this issue and saw that it prints the above generated code described in the issue. 

I have a few questions about this function Visit(). The function seems to call itself recursively but where are the base cases for recursion defined? Also what does dfdS signify here and how it it related to the function dfdx()? Why is it that we never call Visit with dfdS?  Also it is claimed that m_Stack is used to pass arguments to further nodes in visit(). How are these arguments used?

Also can this issue be assigned to me?

**Comment by Nirhar** [comment] 2022-03-27 14:49
After analysing the code base, I think the cause of this problem is an inconsistency in how the function ```DiffRequest::UpdateDiffParamsInfo``` updates the DiffParams, and in what form the function ```ReverseModeVisitor::Derive``` expects the DiffParams to be available. 

For example, in the case that we want to compute the complete Jacobian matrix, ```ReverseModeVisitor::Derive``` expects the ```requests.DiffParams``` array to contain {i, j, res} and it accounts for the last element of the array to be the result array(which is not a parameter to be differentiated) and pops it out, after which the array becomes {i, j}. On a similar line, when we want only a column of the jacobian matrix(say the column pertaining to variable "j") ```ReverseModeVisitor::Derive``` expects the ```requests.DiffParams``` array to contain {j, res} so that after popping "res" the array becomes {j}, which contains the actual variable that we want to differentiate with respect to.

But However, in the first case, where we want to obtain the whole jacobian matrix, ```DiffRequest::UpdateDiffParamsInfo``` updates the DiffParams to {i, j, res} as expected by ```ReverseModeVisitor::Derive```. But, in the second case, ```DiffRequest::UpdateDiffParamsInfo``` updates the DiffParams to {j} only, violating what ```ReverseModeVisitor::Derive``` expects from it. Thus ```ReverseModeVisitor::Derive``` pops the last element, and the DiffParams becomes {}, indicating that there are no parameters to differentiate with respect to, thus giving rise to the problem described in this issue.

I did run some experiments where I bypassed ```ReverseModeVisitor::Derive``` popping the last element of DiffParams, for the second case, and we are then getting the correct jacobian vector with respect to "j".

Now that the cause of the problem is identified, in my opinion, we have 2 ways in which it can be resolved:
1. Modify ```DiffRequest::UpdateDiffParamsInfo``` to not add the result parameter to DiffParams for the full jacobian calculation case and update ```ReverseModeVisitor::Derive``` to not pop the last element in DiffParams
2. Modify ```DiffRequest::UpdateDiffParamsInfo``` to add the result parameter to DiffParams for the jacobian column vector calculation case.

Which one is preferred? or is there any other way of resolving this issue?

**Comment by parth-07** [comment] 2022-03-29 13:38
@Nirhar Thanks for working on this. 

> I did run some experiments where I bypassed ReverseModeVisitor::Derive popping the last element of DiffParams, for the second case, and we are then getting the correct jacobian vector with respect to "j".

That's great. 

I would prefer approach 1 that you have described. But we should also ask Vassil. @vgvassilev,  which approach would you prefer to solve this issue?

**Comment by vgvassilev** [comment] 2022-03-30 08:49
I agree with @parth-07, let's go for approach 1.

**Closed** 2022-04-12 23:00 UTC
Labels: good first issue
