### ISSUE TITLE
Problem with variable sized arrays declared in local scope.

### ISSUE THREAD

**Issue by grimmmyshini** [vgvassilev/clad#519] opened 2023-01-05 08:47 UTC
Currently, the variable declaration and derivative declaration are put in the forward block, this means anything that is declared in a local scope (including loops) will not be correctly declared. A possible solution is described [here](https://github.com/vgvassilev/clad/pull/513#issuecomment-1356784704) as a part of #513.

**Comment by vgvassilev** [comment] 2023-05-28 20:28
@Ris-Bali, could you take a look at this issue and see if it still reproduces?

**Comment by Ris-Bali** [comment] 2023-07-15 18:14
@vgvassilev The issue still reproduces I have tested code after the latest PR adding support for clang-16 

```
#include "clad/Differentiator/Differentiator.h"


double fn(double x, double y, int n) {
    double arr[n];
    double val = arr[0]/2;
    return x * y * val;
}


int main() {
    auto d_fn = clad::gradient(fn);
}

```

```
0.      Program arguments: /home/rishabhbali/CLAD/inst/bin/clang-14 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -main-file-name demo.cpp -mrelocation-model static -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=/home/rishabhbali/CLAD/clad/demos -resource-dir /home/rishabhbali/CLAD/inst/lib/clang/16 -I ../include/ -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/backward -internal-isystem /home/rishabhbali/CLAD/inst/lib/clang/16/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir=/home/rishabhbali/CLAD/clad/demos -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -add-plugin clad -load ../../clad_inst/lib/clad.so -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/demo-7b11b2.o -x c++ demo.cpp
1.      <eof> parser at end of file
2.      LLVM IR generation of declaration 'fn_grad'
3.      Generating code for declaration 'fn_grad'
 #0 0x00007fed12be0c9f llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/rishabhbali/CLAD/llvm-project/llvm/lib/Support/Unix/Signals.inc:567:22
 #1 0x00007fed12be0d62 PrintStackTraceSignalHandler(void*) /home/rishabhbali/CLAD/llvm-project/llvm/lib/Support/Unix/Signals.inc:641:1
 #2 0x00007fed12bdeb90 llvm::sys::RunSignalHandlers() /home/rishabhbali/CLAD/llvm-project/llvm/lib/Support/Signals.cpp:104:20
 #3 0x00007fed12be06d7 SignalHandler(int) /home/rishabhbali/CLAD/llvm-project/llvm/lib/Support/Unix/Signals.inc:412:1
 #4 0x00007fed1765af90 (/lib/x86_64-linux-gnu/libc.so.6+0x3bf90)
 #5 0x00007fed176a9ccc (/lib/x86_64-linux-gnu/libc.so.6+0x8accc)
 #6 0x00007fed1765aef2 raise (/lib/x86_64-linux-gnu/libc.so.6+0x3bef2)
 #7 0x00007fed17645472 abort (/lib/x86_64-linux-gnu/libc.so.6+0x26472)
 #8 0x00007fed12a8d091 bindingsErrorHandler(void*, char const*, bool) /home/rishabhbali/CLAD/llvm-project/llvm/lib/Support/ErrorHandling.cpp:221:55
 #9 0x00007fed1aead859 clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(clang::DeclRefExpr const*) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGExpr.cpp:2850:23
#10 0x00007fed1aea47d7 clang::CodeGen::CodeGenFunction::EmitLValue(clang::Expr const*) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGExpr.cpp:1305:50
#11 0x00007fed1aea42e9 clang::CodeGen::CodeGenFunction::EmitCheckedLValue(clang::Expr const*, clang::CodeGen::CodeGenFunction::TypeCheckKind) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGExpr.cpp:1242:20
#12 0x00007fed1af27f61 (anonymous namespace)::ScalarExprEmitter::EmitCheckedLValue(clang::Expr const*, clang::CodeGen::CodeGenFunction::TypeCheckKind) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGExprScalar.cpp:241:40
#13 0x00007fed1af28262 (anonymous namespace)::ScalarExprEmitter::EmitLoadOfLValue(clang::Expr const*) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGExprScalar.cpp:289:32
#14 0x00007fed1af28f0b (anonymous namespace)::ScalarExprEmitter::VisitDeclRefExpr(clang::DeclRefExpr*) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGExprScalar.cpp:508:30
#15 0x00007fed1af449b4 clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::Visit(clang::Stmt*) /home/rishabhbali/CLAD/obj/tools/clang/include/clang/AST/StmtNodes.inc:1109:1
#16 0x00007fed1af285b6 (anonymous namespace)::ScalarExprEmitter::Visit(clang::Expr*) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGExprScalar.cpp:407:57
#17 0x00007fed1af320bb (anonymous namespace)::ScalarExprEmitter::VisitCastExpr(clang::CastExpr*) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGExprScalar.cpp:2311:17
#18 0x00007fed1af4656d clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::VisitImplicitCastExpr(clang::ImplicitCastExpr*) /home/rishabhbali/CLAD/obj/tools/clang/include/clang/AST/StmtNodes.inc:1049:1
#19 0x00007fed1af448f4 clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::Visit(clang::Stmt*) /home/rishabhbali/CLAD/obj/tools/clang/include/clang/AST/StmtNodes.inc:1049:1
#20 0x00007fed1af285b6 (anonymous namespace)::ScalarExprEmitter::Visit(clang::Expr*) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGExprScalar.cpp:407:57
#21 0x00007fed1af41a22 clang::CodeGen::CodeGenFunction::EmitScalarExpr(clang::Expr const*, bool) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGExprScalar.cpp:5045:1
#22 0x00007fed1b1a058e clang::CodeGen::CodeGenFunction::EmitVariablyModifiedType(clang::QualType) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CodeGenFunction.cpp:2295:54
#23 0x00007fed1ae66177 clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(clang::VarDecl const&) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGDecl.cpp:1445:26
#24 0x00007fed1ae65695 clang::CodeGen::CodeGenFunction::EmitAutoVarDecl(clang::VarDecl const&) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGDecl.cpp:1329:18
#25 0x00007fed1ae600c8 clang::CodeGen::CodeGenFunction::EmitVarDecl(clang::VarDecl const&) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGDecl.cpp:218:27
#26 0x00007fed1ae5fdb8 clang::CodeGen::CodeGenFunction::EmitDecl(clang::Decl const&) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGDecl.cpp:164:47
#27 0x00007fed1b0e35a3 clang::CodeGen::CodeGenFunction::EmitDeclStmt(clang::DeclStmt const&) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGStmt.cpp:1387:3
#28 0x00007fed1b0decfd clang::CodeGen::CodeGenFunction::EmitSimpleStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGStmt.cpp:446:5
#29 0x00007fed1b0ddcc6 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGStmt.cpp:59:3
#30 0x00007fed1b0df22e clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CGStmt.cpp:500:3
#31 0x00007fed1b19c60f clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::Stmt const*) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CodeGenFunction.cpp:1248:33
#32 0x00007fed1b19d4bc clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CodeGenFunction.cpp:1456:21
#33 0x00007fed1b1c9b03 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CodeGenModule.cpp:5402:3
#34 0x00007fed1b1c22a6 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CodeGenModule.cpp:3646:47
#35 0x00007fed1b1c1246 clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CodeGenModule.cpp:3387:5
#36 0x00007fed1b1cdfc0 clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CodeGenModule.cpp:6297:37
#37 0x00007fed1b361ec6 (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/ModuleBuilder.cpp:189:7
#38 0x00007fed1b18701a clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:235:11
#39 0x00007fed17d20fde clang::MultiplexConsumer::HandleTopLevelDecl(clang::DeclGroupRef) /home/rishabhbali/CLAD/llvm-project/clang/lib/Frontend/MultiplexConsumer.cpp:277:25
#40 0x00007fed07e93a46 clad::plugin::CladPlugin::ProcessTopLevelDecl(clang::Decl*) /home/rishabhbali/CLAD/clad/tools/ClangPlugin.cpp:165:36
#41 0x00007fed07e941c7 clad::plugin::CladPlugin::ProcessDiffRequest(clad::DiffRequest&) /home/rishabhbali/CLAD/clad/tools/ClangPlugin.cpp:287:13
#42 0x00007fed07e939ba clad::plugin::CladPlugin::HandleTopLevelDecl(clang::DeclGroupRef) /home/rishabhbali/CLAD/clad/tools/ClangPlugin.cpp:157:7
#43 0x00007fed17d20fde clang::MultiplexConsumer::HandleTopLevelDecl(clang::DeclGroupRef) /home/rishabhbali/CLAD/llvm-project/clang/lib/Frontend/MultiplexConsumer.cpp:277:25
#44 0x00007fed0d2f3391 clang::ParseAST(clang::Sema&, bool, bool) /home/rishabhbali/CLAD/llvm-project/clang/lib/Parse/ParseAST.cpp:166:20
#45 0x00007fed17ce1add clang::ASTFrontendAction::ExecuteAction() /home/rishabhbali/CLAD/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1165:11
#46 0x00007fed1b1830ad clang::CodeGenAction::ExecuteAction() /home/rishabhbali/CLAD/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:1172:5
#47 0x00007fed17ce1433 clang::FrontendAction::Execute() /home/rishabhbali/CLAD/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1062:38
#48 0x00007fed17c026e6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/rishabhbali/CLAD/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:1046:42
#49 0x00007fed1c59363e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/rishabhbali/CLAD/llvm-project/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:264:38
#50 0x000055fe53b59624 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /home/rishabhbali/CLAD/llvm-project/clang/tools/driver/cc1_main.cpp:251:40
#51 0x000055fe53b48146 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) /home/rishabhbali/CLAD/llvm-project/clang/tools/driver/driver.cpp:360:20
#52 0x000055fe53b488b0 clang_main(int, char**) /home/rishabhbali/CLAD/llvm-project/clang/tools/driver/driver.cpp:435:26
#53 0x000055fe53b7a583 main /home/rishabhbali/CLAD/obj/tools/clang/tools/driver/clang-driver.cpp:11:63
#54 0x00007fed1764618a (/lib/x86_64-linux-gnu/libc.so.6+0x2718a)
#55 0x00007fed17646245 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x27245)
#56 0x000055fe53b46751 _start (/home/rishabhbali/CLAD/inst/bin/clang-14+0x35751)
clang-14: error: unable to execute command: Aborted
clang-14: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 16.0.6 (https://github.com/llvm/llvm-project.git 7cbf1a2591520c2491aa35339f227775f4d3adf6)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by vgvassilev** [comment] 2023-07-15 19:09
@Ris-Bali do you have an idea how to address this issue?

**Comment by Ris-Bali** [comment] 2023-07-16 12:46
> @Ris-Bali do you have an idea how to address this issue?

I'll try the solution mentioned in the PR; even though it seems to have limitations for edge cases.

**Comment by PetroZarytskyi** [comment] 2024-05-22 15:05
This issue seems to be fixed on master. Please reopen if a new reproducer is found.

**Closed by PetroZarytskyi** 2024-05-22 15:05 UTC
