### ISSUE TITLE
Clad unable to find function definition in same translation unit

### ISSUE THREAD

**Issue by maxaehle** [vgvassilev/clad#652] opened 2023-11-17 13:55 UTC
**Summary**: In the setup described below, Clad says that it does not find a function definition, even though it exists in the same translation unit.

**Minimal example**: Compile the following code with Clang++ with the clad plugin:

```c++
#include <iostream>
#include "clad/Differentiator/Differentiator.h"

double f(double x, double y);

int main(){
  std::cout << "val = " << f(3,4) << std::endl;
  auto f_dx = clad::differentiate(f, "x");
  std::cout << "diff = " << f_dx.execute(3,4) << std::endl;
}

double f(double x, double y){
  return x*y;
}
```

**Expected behavior**: Code compiles.

**Observed behavior**: Compiler error:
```
example.cpp:8:15: error: attempted differentiation of function 'f', which does not have a definition
  auto f_dx = clad::differentiate(f, "x");
              ^
1 error generated.
```

**Setup**: Clad built from the GitHub master branch at commit 1bdd261 on Ubuntu 22.04 with LLVM 11.

**Comment by vgvassilev** [comment] 2023-11-18 10:16
Hi @maxaehle, thanks for the bug report.

Currently, Clad processes every differentiation request (a call to `clad::differentiate`) at each top-level function declaration. That is, when we see main, we have to have the definition because we will generate a derivative.

The reason is that we are under the assumption that after the request to differentiate we will _use_ the gradient in the same context. I think we can relax that and process all differentiation requests at the end of the translation unit.

In the meanwhile, is it possible to re-arrange your code to follow the current rule?

**Comment by davidlange6** [comment] 2024-01-17 17:16
duplicate of #248 (still open)

**Closed by davidlange6** 2024-01-17 17:16 UTC
